#!/usr/bin/env bash

OUTPUT_FP="$1"

# CODEGEN_BEGIN_LINE="### CODEGEN BEGIN (src: devtools/codegen/gen_sql_queries_validation ${QUERIES_TEST_FP})"
# CODEGEN_END_LINE='### CODEGEN END'

CODEGEN_FILE_HEADER='// THIS CODE IS GENERATED - DO NOT CHANGE IT'

read -r -d '' CODEGEN_DEPS << 'EOF'
func validateSyntax(query string) error {
	if isDoStatement(query) {
		return nil
	}
	validateQuery := fmt.Sprintf(`
		DO $SYNTAX_CHECK$ BEGIN RETURN;
		%s;
		END; $SYNTAX_CHECK$;`,
		query)
	_, err := setup.PG.Exec(context.Background(), validateQuery)
	return err
}

func isDoStatement(query string) bool {
	return strings.HasPrefix(strings.TrimSpace(query), "DO")
}

func validate(sqlQuery string, msgAndArgs ...interface{}) func() error {
	return func() error {
		for i, query := range xmust.Do(sql.ParseQueries(sqlQuery)) {
			err := validateSyntax(query)
			if err != nil {
				msg := xfmt.Sprintfg(msgAndArgs...)
				return fmt.Errorf("%s (query #%d): %w", msg, i+1, err)
			}
		}
		return nil
	}
}
EOF


code=$(grep "read(" src/sql/queries.go | sort | sed -E -e 's/^[[:space:]]*([a-zA-Z0-9_]+):.+read\("(.*)"\).*/validate(m.\1, "\2"),/')

tmp=$(mktemp)
echo "$CODEGEN_FILE_HEADER" >> "$tmp"
echo "package sql_tests" >> "$tmp"
echo "" >> "$tmp"
echo "$CODEGEN_DEPS" >> "$tmp"
echo "" >> "$tmp"
echo "func queryValidates(m *sql.QueryManager) []func() error {" >> "$tmp"
echo "return []func() error{" >> "$tmp"
echo "$code" >> "$tmp"
echo "}" >> "$tmp"
echo "}" >> "$tmp"

mv "$tmp" "$OUTPUT_FP"

gofmt -s -w "$OUTPUT_FP"
goimports -w "$OUTPUT_FP"
